create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_item_pedido (preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, id bigint not null auto_increment, pedido_id bigint not null, produto_id bigint not null, observacao varchar(255), primary key (id)) engine=InnoDB;
create table tb_pedido (status tinyint, subtotal decimal(38,2), taxa_frete decimal(38,2), valor_total decimal(38,2), data_cancelamento datetime(6), data_confirmacao datetime(6), data_criacao datetime(6), data_entrega datetime(6), endereco_cidade_id bigint, forma_pagamento_id bigint not null, id bigint not null auto_increment, restaurante_id bigint not null, usuario_cliente_id bigint not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), primary key (id)) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido (id);
alter table tb_item_pedido add constraint FKgfmv77km3wt2evaaq2vkiv2oj foreign key (produto_id) references tb_produto (id);
alter table tb_pedido add constraint FKtfw0k4hiarlmrlovrn9iix582 foreign key (usuario_cliente_id) references tb_usuario (id);
alter table tb_pedido add constraint FKl27uu7cus7s3lwsg8gxh7kvm2 foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_pedido add constraint FK4gcd7u6xju8bmmgxx8c303job foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_pedido add constraint FKbb7n8l77yto4r2hix87w3x4oy foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_item_pedido (preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, id bigint not null auto_increment, pedido_id bigint not null, produto_id bigint not null, observacao varchar(255), primary key (id)) engine=InnoDB;
create table tb_pedido (status tinyint, subtotal decimal(38,2), taxa_frete decimal(38,2), valor_total decimal(38,2), data_cancelamento datetime(6), data_confirmacao datetime(6), data_criacao datetime(6), data_entrega datetime(6), endereco_cidade_id bigint, forma_pagamento_id bigint not null, id bigint not null auto_increment, restaurante_id bigint not null, usuario_cliente_id bigint not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), primary key (id)) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido (id);
alter table tb_item_pedido add constraint FKgfmv77km3wt2evaaq2vkiv2oj foreign key (produto_id) references tb_produto (id);
alter table tb_pedido add constraint FKtfw0k4hiarlmrlovrn9iix582 foreign key (usuario_cliente_id) references tb_usuario (id);
alter table tb_pedido add constraint FKl27uu7cus7s3lwsg8gxh7kvm2 foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_pedido add constraint FK4gcd7u6xju8bmmgxx8c303job foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_pedido add constraint FKbb7n8l77yto4r2hix87w3x4oy foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_item_pedido (preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, id bigint not null auto_increment, pedido_id bigint not null, produto_id bigint not null, observacao varchar(255), primary key (id)) engine=InnoDB;
create table tb_pedido (status tinyint, subtotal decimal(38,2), taxa_frete decimal(38,2), valor_total decimal(38,2), data_cancelamento datetime(6), data_confirmacao datetime(6), data_criacao datetime(6), data_entrega datetime(6), endereco_cidade_id bigint, forma_pagamento_id bigint not null, id bigint not null auto_increment, restaurante_id bigint not null, usuario_cliente_id bigint not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), primary key (id)) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido (id);
alter table tb_item_pedido add constraint FKgfmv77km3wt2evaaq2vkiv2oj foreign key (produto_id) references tb_produto (id);
alter table tb_pedido add constraint FKtfw0k4hiarlmrlovrn9iix582 foreign key (usuario_cliente_id) references tb_usuario (id);
alter table tb_pedido add constraint FKl27uu7cus7s3lwsg8gxh7kvm2 foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_pedido add constraint FK4gcd7u6xju8bmmgxx8c303job foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_pedido add constraint FKbb7n8l77yto4r2hix87w3x4oy foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_item_pedido (preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, id bigint not null auto_increment, pedido_id bigint not null, produto_id bigint not null, observacao varchar(255), primary key (id)) engine=InnoDB;
create table tb_pedido (status tinyint, subtotal decimal(38,2), taxa_frete decimal(38,2), valor_total decimal(38,2), data_cancelamento datetime(6), data_confirmacao datetime(6), data_criacao datetime(6), data_entrega datetime(6), endereco_cidade_id bigint, forma_pagamento_id bigint not null, id bigint not null auto_increment, restaurante_id bigint not null, usuario_cliente_id bigint not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), primary key (id)) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido (id);
alter table tb_item_pedido add constraint FKgfmv77km3wt2evaaq2vkiv2oj foreign key (produto_id) references tb_produto (id);
alter table tb_pedido add constraint FKtfw0k4hiarlmrlovrn9iix582 foreign key (usuario_cliente_id) references tb_usuario (id);
alter table tb_pedido add constraint FKl27uu7cus7s3lwsg8gxh7kvm2 foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_pedido add constraint FK4gcd7u6xju8bmmgxx8c303job foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_pedido add constraint FKbb7n8l77yto4r2hix87w3x4oy foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_item_pedido (preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, id bigint not null auto_increment, pedido_id bigint not null, produto_id bigint not null, observacao varchar(255), primary key (id)) engine=InnoDB;
create table tb_pedido (status tinyint, subtotal decimal(38,2), taxa_frete decimal(38,2), valor_total decimal(38,2), data_cancelamento datetime(6), data_confirmacao datetime(6), data_criacao datetime(6), data_entrega datetime(6), endereco_cidade_id bigint, forma_pagamento_id bigint not null, id bigint not null auto_increment, restaurante_id bigint not null, usuario_cliente_id bigint not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), primary key (id)) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido (id);
alter table tb_item_pedido add constraint FKgfmv77km3wt2evaaq2vkiv2oj foreign key (produto_id) references tb_produto (id);
alter table tb_pedido add constraint FKtfw0k4hiarlmrlovrn9iix582 foreign key (usuario_cliente_id) references tb_usuario (id);
alter table tb_pedido add constraint FKl27uu7cus7s3lwsg8gxh7kvm2 foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_pedido add constraint FK4gcd7u6xju8bmmgxx8c303job foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_pedido add constraint FKbb7n8l77yto4r2hix87w3x4oy foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_item_pedido (preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, id bigint not null auto_increment, pedido_id bigint not null, produto_id bigint not null, observacao varchar(255), primary key (id)) engine=InnoDB;
create table tb_pedido (status tinyint, subtotal decimal(38,2), taxa_frete decimal(38,2), valor_total decimal(38,2), data_cancelamento datetime(6), data_confirmacao datetime(6), data_criacao datetime(6), data_entrega datetime(6), endereco_cidade_id bigint, forma_pagamento_id bigint not null, id bigint not null auto_increment, restaurante_id bigint not null, usuario_cliente_id bigint not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), primary key (id)) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido (id);
alter table tb_item_pedido add constraint FKgfmv77km3wt2evaaq2vkiv2oj foreign key (produto_id) references tb_produto (id);
alter table tb_pedido add constraint FKtfw0k4hiarlmrlovrn9iix582 foreign key (usuario_cliente_id) references tb_usuario (id);
alter table tb_pedido add constraint FKl27uu7cus7s3lwsg8gxh7kvm2 foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_pedido add constraint FK4gcd7u6xju8bmmgxx8c303job foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_pedido add constraint FKbb7n8l77yto4r2hix87w3x4oy foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
create table tb_cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_grupo_permissoes (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table tb_item_pedido (preco_total decimal(38,2), preco_unitario decimal(38,2), quantidade integer, id bigint not null auto_increment, pedido_id bigint not null, produto_id bigint not null, observacao varchar(255), primary key (id)) engine=InnoDB;
create table tb_pedido (status tinyint, subtotal decimal(38,2), taxa_frete decimal(38,2), valor_total decimal(38,2), data_cancelamento datetime(6), data_confirmacao datetime(6), data_criacao datetime(6), data_entrega datetime(6), endereco_cidade_id bigint, forma_pagamento_id bigint not null, id bigint not null auto_increment, restaurante_id bigint not null, usuario_cliente_id bigint not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), primary key (id)) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table tb_usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_usuarios_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table tb_restaurante_produtos add constraint UKhpq6msev4jlkr06auw0b9krj1 unique (produtos_id);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado (id);
alter table tb_grupo_permissoes add constraint FKn9k90xxcrxyy9ijrsk1g42ufp foreign key (permissao_id) references tb_permissao (id);
alter table tb_grupo_permissoes add constraint FKlmqa53xvj0qyw8vkccxls4372 foreign key (grupo_id) references tb_grupo (id);
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido (id);
alter table tb_item_pedido add constraint FKgfmv77km3wt2evaaq2vkiv2oj foreign key (produto_id) references tb_produto (id);
alter table tb_pedido add constraint FKtfw0k4hiarlmrlovrn9iix582 foreign key (usuario_cliente_id) references tb_usuario (id);
alter table tb_pedido add constraint FKl27uu7cus7s3lwsg8gxh7kvm2 foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_pedido add constraint FK4gcd7u6xju8bmmgxx8c303job foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_pedido add constraint FKbb7n8l77yto4r2hix87w3x4oy foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_produto add constraint FK1fh03prrjxetvrl6d4ut5r1r0 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante add constraint FKpsus3qnrv5sxgm95m8epaievn foreign key (cozinha_id) references tb_cozinha (id);
alter table tb_restaurante add constraint FKp5f7gcswjq064qro5pfjoj49r foreign key (endereco_cidade_id) references tb_cidade (id);
alter table tb_restaurante_forma_pagamento add constraint FKsi78wf2v77p8yv9swve1qd4bx foreign key (forma_pagamento_id) references tb_forma_pagamento (id);
alter table tb_restaurante_forma_pagamento add constraint FKngs0dntt47n5xpnued71e7oc5 foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_restaurante_produtos add constraint FK3pf9asea4x2u74erk8k6hmh4m foreign key (produtos_id) references tb_produto (id);
alter table tb_restaurante_produtos add constraint FKe3seuam7je10059miq2o0fd6v foreign key (restaurante_id) references tb_restaurante (id);
alter table tb_usuarios_grupo add constraint FKh89gvqid1wfnnpisputoy5c13 foreign key (grupo_id) references tb_grupo (id);
alter table tb_usuarios_grupo add constraint FKhyvcavlcujj4ts46rckfkurof foreign key (usuario_id) references tb_usuario (id);
insert into tb_cozinha (id, nome) values (1, 'Tailandesa');
insert into tb_cozinha (id, nome) values (2, 'Indiana');
insert into tb_estado (id, nome) values (1, 'Minas Gerais');
insert into tb_estado (id, nome) values (2, 'São Paulo');
insert into tb_estado (id, nome) values (3, 'Ceará');
insert into tb_cidade (id, nome, estado_id) values (1, 'Uberlândia', 1);
insert into tb_cidade (id, nome, estado_id) values (2, 'Belo Horizonte', 1);
insert into tb_cidade (id, nome, estado_id) values (3, 'São Paulo', 2);
insert into tb_cidade (id, nome, estado_id) values (4, 'Campinas', 2);
insert into tb_cidade (id, nome, estado_id) values (5, 'Fortaleza', 3);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro) values (1, 'Thai Gourmet', 10, 1, utc_timestamp, utc_timestamp, 1, '38400-999', 'Rua João Pinheiro', '1000', 'Centro');
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (2, 'Thai Delivery', 9.50, 1, utc_timestamp, utc_timestamp);
insert into tb_restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values (3, 'Tuk Tuk Comida Indiana', 15, 2, utc_timestamp, utc_timestamp);
insert into tb_forma_pagamento (id, descricao) values (1, 'Cartão de crédito');
insert into tb_forma_pagamento (id, descricao) values (2, 'Cartão de débito');
insert into tb_forma_pagamento (id, descricao) values (3, 'Dinheiro');
insert into tb_permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into tb_permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into tb_restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);
