DROP TABLE IF EXISTS tb_users;

CREATE TABLE tb_users (
    --id CHAR(36) PRIMARY KEY,
    id CHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    password VARCHAR(255) NOT NULL,
    login VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) NOT NULL,
    ativado VARCHAR(1) NOT NULL
);
